### PR TITLE
Add JDK 11

### PR DESCRIPTION
**Pull request by whaley**

### CODE REVIEW

**Comment by whaley** [comment]
OpenJDK 11 needs to be added also, but how the current install script handles .dmg files for MacOS needs to change since OpenJDK does not provide a .dmg (see #29 )

**Comment by whaley** [comment]
Commit d51639f  supports MacOS and *should* work for openjdk now.  I'd love someone to verify this.

Also, we've got a fair bit of not-so-easy-to-follow logic to generate the URL to GET from for a small handful of URLs, so in the future it may be helpful to hardcode the URLs into some nested cases based on distribution (openjdk vs. oracle vs. ???) and whether we are targeting linux x86, linux64, or macos.

**Comment by linjunpop** [comment]
It works like a charm. 👏

**Comment by x80486** [comment]
Works for me – although I only tested `openjdk-11` on (Arch) Linux.

It would be great if this one can be merged!

**Comment by trustin** [comment]
Getting 404 for `openjdk-11` unfortunately. Did they change the location again? :sob:

**Comment by trustin** [comment]
Actually, `openjdk-10.0.2` stopped to work as well.

**Comment by trustin** [comment]
The following diff fixes the problem. Please feel free to pull in.

```diff
diff --git bin/install bin/install
index 7928760..dc2989e 100755
--- bin/install
+++ bin/install
@@ -27,8 +27,18 @@ get_variant() {
 	case "$(uname -s)" in
 		Linux)
 			case "$(uname -m)" in
-				x86_64) echo linux-x64.tar.gz ;;
-				i[[3-9]]86) echo linux-i586.tar.gz ;;
+				x86_64)
+					case $distro in
+						oracle) echo linux-x64.tar.gz ;;
+						openjdk) echo linux-x64_bin.tar.gz ;;
+						*) ;;
+					esac ;;
+				i[[3-9]]86)
+					case $distro in
+						oracle) echo linux-i586.tar.gz ;;
+						openjdk) echo linux-i586_bin.tar.gz ;;
+						*) ;;
+					esac ;;
 				*) ASDF_JAVA_ERROR="$(uname -m) is not supported on linux" ;;
 			esac ;;
 		Darwin)
@@ -85,7 +95,7 @@ get_java() {
 		oracle-8.141)   url=$base$oracle8_version-b15/336fa29ff2bb4ef291e347e091f7f4a7/jdk-$oracle8_version-$variant ;;
 		oracle-8.131)   url=$base$oracle8_version-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-$oracle8_version-$variant ;;
 		openjdk-10.0.2) url=$base'10'/$version/19aef61b38124481863b1413dce1855f/13/openjdk-$version'_'$variant ;;
-		openjdk-11)     url=$base$version/28/GPL/openjdk-11+28_$variant ;;
+		openjdk-11)     url=$base'11'/openjdk-11+28_$variant ;;
 		*) ASDF_JAVA_ERROR="$version is not a supported version" ;;
 	esac
 	[[ -z "$ASDF_JAVA_ERROR" ]] || return
```

**Comment by trustin** [comment]
Updated the diff to fix a few issues. Now it works for both 10.0.2 and 11.

**Comment by whaley** [comment]
It's a bit of a crapshoot - it's not the first time the URLs have changed from underneath us

**Comment by whaley** [comment]
@skotchpine if you are still active, could you review this PR and merge in to master if all looks well for yoU?

**Comment by skotchpine** [comment]
Hey I'll come back for a few days. Fuck Oracle atm.

**Comment by trustin** [comment]
Maybe not the right place to report, but oracle-8.181 and oracle-10.0.2 are gone.

**Comment by vraravam** [comment]
Please merge this - im trying to get openjdk 10.0.2 installed on my mac using asdf - and this is a blocker.

**Comment by skotchpine** [comment]
@vraravam @trustin @whaley About to merge this and a bunch of changes. Closing

@linjunpop I miss arch, but I think I was more in love with i3 than pacman

**Pull request closed without merging**
