### PR TITLE
Add version 8u181

### PR DESCRIPTION
**Pull request by psantos10**

### CODE REVIEW

**Comment by whaley** [comment]
Works on my machine:

```
~/.asdf/plugins/java(java_8_181 ✔) asdf install java 8.181
---- ASDF JAVA MESSAGE ----
downloading: http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-macosx-x64.dmg
---- ASDF JAVA MESSAGE ----
expanding java dist
722405 blocks

~/.asdf/plugins/java(java_8_181 ✔) asdf global java 8.181
~/.asdf/plugins/java(java_8_181 ✔) java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

~/.asdf/plugins/java(java_8_181 ✔) git show | head
commit 66eeeb48dfd848152d6fb11321f92643bb8b712a
Author: Patrício dos Santos <eu@patricio.me>
Date:   Thu Jul 19 11:01:19 2018 +0100

    Remove unavailable versions

diff --git a/bin/install b/bin/install
index b5212fb..0d6326a 100755
```

**Comment by kossmoboleat** [comment]
The travis build seems to try to download 10.0.1 first, which fails because it isn't available anymore.

**Comment by whaley** [comment]
@kossmoboleat yeah, the travis runs a script to test asdf, but asdf always pulls down the master repo of plugins, thus 10.0.1 is being used.  So travis is a good check on the master branch of this repo, but will fail everytime for PRs.  This is why I did a manual check.

**Comment by skotchpine** [comment]
Thanks for the help, @psantos10. Sorry to have taken so long to add this in and for clobbering your commit. I'll try to be more diligent next time

**Pull request closed without merging**
